version: '3.9'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'ENTER_YOUR_DATABASE_NAME_HERE'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/ENTER_YOUR_DATABASE_NAME_HERE'
    volumes:
      - postgres:/data/postgres
    ports:
      - '5433:5432'
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U postgres -d ENTER_YOUR_DATABASE_NAME_HERE']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  postgres:
